# see https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Example project
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/helloWorld/helloWorld.zip
      Handler: bin/main
      Runtime: go1.10
      MemorySize: 128
      Timeout: 30 # seconds, 300 max
